"""
Provision a Client FreedomBot
=============================

FB-033: one template bot, cloned per client into its own deployment and its
own database.

    python -m scripts.provision_client --name "Globex Ltd" --slug globex \\
        --admin-email owner@globex.com --admin-password '...' \\
        [--config clients/globex.json] [--out deploy/clients]

Steps, all idempotent:

1. Load ``bizos/templates/freedombot.json`` and merge the client's overrides
   (``--config``: purchased domains, mode, retention, extra seed memory…).
2. Create the client in the control plane and its dedicated workspace database
   (or schema), apply the platform schema with the per-client ``client_id``
   wall on every table, and seed the template's starter memory.
3. Create the client's first admin.
4. Write ``<out>/<slug>/client.env`` and ``<out>/<slug>/compose.yaml`` — a
   separate API + UI deployment pinned to this client with ``CLIENT_SLUG`` so it
   refuses sign-ins and tokens for any other company.

Secrets are generated into ``client.env`` (never committed; ``deploy/`` is
git-ignored). The model key is left blank for the operator to fill in.
"""

from __future__ import annotations

import argparse
import json
import secrets
import sys
from pathlib import Path

from bizos.util.dotenv import load_dotenv

load_dotenv()

from bizos import template  # noqa: E402
from bizos.bootstrap import admin_context  # noqa: E402
from bizos.connectors.registry import seed_default_integrations  # noqa: E402
from bizos.control import store as control  # noqa: E402
from bizos.control.db import migrate_control_plane  # noqa: E402
from bizos.tenancy import provisioning  # noqa: E402
from bizos.types import DeploymentType, Role  # noqa: E402
from bizos.util.ids import slugify  # noqa: E402

COMPOSE = """\
# FreedomBot for {company} — generated by scripts/provision_client.py.
# A separate deployment: its own API and UI, pinned to client "{slug}".
# Uses the shared Postgres server but only this client's database ({db}).
name: freedombot-{slug}

services:
  api:
    image: freedombot-api:{version}
    build: {root}
    env_file: ./client.env
    ports:
      - "{api_port}:8000"
    command: >
      sh -c "python -m scripts.bootstrap &&
             python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"

  ui:
    build:
      context: {root}/ui
      args:
        NEXT_PUBLIC_API_URL: http://localhost:{api_port}
    depends_on:
      - api
    ports:
      - "{ui_port}:3000"
"""


def _env_file(client, *, db_host: str, api_port: int, ui_port: int) -> str:
    return "\n".join(
        [
            f"# FreedomBot deployment for {client.company_name} ({client.slug})",
            "RUNTIME_ENV=prd",
            f"CLIENT_SLUG={client.slug}",
            f"DB_HOST={db_host}",
            "DB_PORT=5432",
            "DB_USER=bizos",
            "DB_PASS=bizos",
            "CONTROL_DB_NAME=bizos_control",
            "WORKSPACE_DB_PREFIX=bizos_ws_",
            f"DEFAULT_DEPLOYMENT_TYPE={client.deployment_type}",
            f"JWT_SECRET={secrets.token_urlsafe(48)}",
            f"SECRET_ENCRYPTION_KEY={secrets.token_urlsafe(48)}",
            f"CORS_ORIGINS=http://localhost:{ui_port}",
            f"AGENTOS_URL=http://127.0.0.1:{api_port}",
            "OPENAI_API_KEY=",
            "MODEL_ID=gpt-4.1-mini",
            "",
        ]
    )


def provision(args: argparse.Namespace) -> dict:
    migrate_control_plane()
    overrides = json.loads(Path(args.config).read_text()) if args.config else {}
    config = template.merge(template.load_template(), overrides)
    slug = slugify(args.slug or args.name)
    settings = template.settings_from(config, company_name=args.name)

    try:
        client = control.get_client_by_slug(slug)
        created = False
    except control.ClientNotFound:
        client = control.create_client(
            company_name=args.name,
            slug=slug,
            deployment_type=DeploymentType.parse(config.get("deployment_type"), DeploymentType.DEDICATED_DB),
            settings=settings,
            created_by="provision_client",
        )
        created = True

    report = provisioning.provision_client(client)
    ctx = admin_context(client)
    seed_default_integrations(ctx)
    seeded = template.seed_memory(ctx, config, client.settings)
    unwalled = provisioning.unwalled_tables(ctx)
    if unwalled:
        raise SystemExit(f"client wall missing on: {', '.join(unwalled)}")

    admin = None
    if args.admin_email:
        try:
            admin = control.create_user(
                client_id=client.id,
                email=args.admin_email,
                password=args.admin_password or secrets.token_urlsafe(16),
                display_name="Client admin",
                roles=(Role.ADMIN,),
                created_by="provision_client",
            ).email
        except control.DuplicateUser:
            admin = args.admin_email

    out_dir = Path(args.out) / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    env_path = out_dir / "client.env"
    if not env_path.exists():
        env_path.write_text(
            _env_file(client, db_host=args.db_host, api_port=args.api_port, ui_port=args.ui_port)
        )
        env_path.chmod(0o600)
    (out_dir / "compose.yaml").write_text(
        COMPOSE.format(
            company=client.company_name,
            slug=slug,
            db=client.db_name,
            version=config.get("template_version", "1"),
            root=Path(__file__).resolve().parent.parent,
            api_port=args.api_port,
            ui_port=args.ui_port,
        )
    )
    return {
        "client_id": client.id,
        "slug": slug,
        "created": created,
        "database": client.db_name,
        "schema": client.db_schema,
        "template_version": config.get("template_version"),
        "purchased_domains": client.settings.purchased_domains,
        "seeded_memory": seeded,
        "admin": admin,
        "deployment": str(out_dir),
        "provisioning": report,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Provision a per-client FreedomBot.")
    parser.add_argument("--name", required=True, help="company name")
    parser.add_argument("--slug", help="client slug (default: from name)")
    parser.add_argument("--config", help="JSON overrides applied on top of the template")
    parser.add_argument("--admin-email")
    parser.add_argument("--admin-password")
    parser.add_argument("--out", default="deploy/clients")
    parser.add_argument("--db-host", default="host.docker.internal")
    parser.add_argument("--api-port", type=int, default=8101)
    parser.add_argument("--ui-port", type=int, default=3101)
    args = parser.parse_args()
    print(json.dumps(provision(args), indent=2, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main())
